// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MessageController from "./message_controller"
application.register("message", MessageController)

import RoomController from "./room_controller"
application.register("room", RoomController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ActiveItemController from "./active_item_controller"
application.register("active-item", ActiveItemController)

import NoticesController from "./notices_controller"
application.register("notices", NoticesController)
