version: "3.9"

services:

  pg-test:
    image: postgres:16.1
    container_name: pg-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - test-net

  chat-test:
    image: chat-test
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: chat-test
    environment:
      RAILS_ENV: test
      PG_HOST: pg-test
      SECRET_KEY_BASE: 948b55112005daf9de77df810ed1d73563f13a41303ee158d75dca9399cf128a572e91c588325fd81dd4e5746881007eb11bcca186cbd9800977244e78137b33
    depends_on:
      - pg-test
    volumes:
      - gems:/usr/local/bundle/
      - node_modules:/app/node_modules
    networks:
      - test-net
    entrypoint: ./docker-entrypoint-test.sh

volumes:
  gems:
  node_modules:

networks:
  test-net:
