services:
  pg-test:
    image: postgres:16.1
    container_name: pg-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - test-net

  chat-test:
    image: chat-test
    build: .
    container_name: chat-test
    environment:
      RAILS_ENV: test
      PG_HOST: pg-test
    depends_on:
      - pg-test
    volumes:
      - gems:/usr/local/bundle/
      - ./node_modules:/app/node_modules
    networks:
      - test-net
    entrypoint: [ "sh", "-c", "bundle exec rails db:prepare && bundle exec rspec --format documentation" ]

volumes:
  gems:

networks:
  test-net:
