version: "3.9"

services:

  pg:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chat-net

  chat:
    image: chat
    build: .
    container_name: chat
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      TZ: Europe/Moscow
      RAILS_MASTER_KEY: 708a9bc145ef92d6b3e5b3f9ee44d6fb
    depends_on:
      - pg
      - redis
    ports:
      - "80:3000"
    volumes:
      - gems:/usr/local/bundle/
      - ./node_modules:/app/node_modules
    networks:
      - chat-net
    restart: always

  redis:
    image: redis:latest
    container_name: redis_server
    command: redis-server
    restart:
    ports:
      - "6379:6379"
    networks:
      - chat-net
    volumes:
      - redis:/data

volumes:
  gems:
  db_data:
  redis:

networks:
  chat-net:
