default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>
  database: chat_test

production:
  <<: *default
  host: pg
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: chat_production
